### ISSUE TITLE
missing file ‘build/setup.mk'

### ISSUE THREAD

**Issue by tgly307** [wbernest/mattermost-plugin-rssfeed#1]
I want to build this plugin and excute `make`, then I got the error `make: *** No rule to make target 'build/setup.mk'.  Stop.` 
How can I get this file? Or I missed something?

**Comment by wbernest** [comment]
Yes.  You were missing a build folder that I had accidentally added to the gitignore file.  I just pushed it to the repo if you want to repull and try again.  You may want to use make dist (which just builds the package and does do any of the style-checking) instead of just make.  There are some gofmt issues that I have not been able to resolve.

**Comment by tgly307** [comment]
thx a lot, now I can build it by make dist.
By the way, I prefer the plugin provide icons itself instead of calling external resources. Because external resources are uncertain, such as the inability to access Internet resources in a LAN environment. (This is my situation)

**Comment by wbernest** [comment]
I don't think it is even using the icon I pointed it to.  I could probably remove that code altogether.

**Comment by tgly307** [comment]
I changed the icon url to mine, it works. So I think the problem is on the Wikipedia icon, it is not a direct image format.

**Comment by wbernest** [comment]
Got it in there with the new release.
